<div> 
    <div class="container py-12">
        <h1 class="heading text-xl md:text-2xl">PRIVACY STATEMENT</h1>
        <h3 class="font-bold mt-3 mb-1 text-xl">WHAT DO WE DO WITH YOUR INFORMATION?</h3>
        <p>When you register on our website, or purchase something from our store, as part of the buying process, we collect the personal information you give us such as your name or your family member’s name, age, address, your email ID, your mobile number, referral details, gifting details and any other information shared by you.</p>
        <p>When you browse our website, we also automatically receive your computer or mobile phone’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.</p>
        <p>Email marketing, SMS updates, App Push notifications and any other communication: Your submission of contact information is considered as deemed approval and acceptance to share regular updates, information about our store, new products and other updates.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">CONSENT</h2>
        <h3 class="font-bold mt-3 mb-1">How do you get my consent?</h3>
        <p>When you provide us with personal information to complete a transaction, verify your credit card, place an order, we imply that you consent to our collecting it and using it for that specific reason only.</p>
        <p>Your submission of any additional contact information is considered as deemed approval and acceptance to share regular updates, information about our store, new products and other updates.</p>
        <h3 class="font-bold mt-3 mb-1">How do I withdraw my consent?</h3>
        <p>If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at any time, by informing us in writing over email at {{ config('deep.email') }}.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">DISCLOSURE</h2>
        <p>We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">PAYMENT</h2>
        <p>We use Razorpay for processing payments. We/Razorpay do not store your card data on their servers. The data is encrypted through the Payment Card Industry Data Security Standard (PCI-DSS) when processing payment. Your purchase transaction data is only used as long as is necessary to complete your purchase transaction. After that is complete, your purchase transaction information is not saved.</p>
        <p>Our payment gateway adheres to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover.</p>
        <p>PCI-DSS requirements help ensure the secure handling of credit card information by our store and its service providers.</p>
        <p>For more insight, you may also want to read terms and conditions of razorpay on https://razorpay.com.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">THIRD-PARTY SERVICES</h2>
        <p>While we strive to work with reputable companies with good privacy practices, these privacy policies do not apply to services offered by other companies, individuals or third parties, including products or sites that may be displayed to you on our service. We also do not control the privacy policies and your privacy settings with third-parties, including social networks and ad networks. We may use third parties to help offer you more tailored ads and better services, such as obtaining analytics about the users of our site and to help tailor advertising to your preferences. For further information, please see the relevant privacy policies for each third party and industry codes of conduct.</p>
        <p>In general, the third-party providers used by us will only collect, use and disclose your information to the extent necessary to allow them to perform the services they provide to us.</p>
        <p>However, certain third-party service providers, such as payment gateways and other payment transaction processors, have their own privacy policies in respect to the information we are required to provide to them for your purchase-related transactions.</p>
        <p>For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.</p>
        <p>In particular, remember that certain providers may be located in or have facilities that are located a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.</p>
        <p>Once you leave our store's website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our website’s Terms of Service.</p>
        <p>Links - When you click on links on our store, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">ACCESSING, UPDATING, AND DELETING YOUR PERSONAL DATA</h2>
        <p>You can access your personal data that {{ config('deep.brand') }} collects by logging into your account. To terminate your account please send an email on {{ config('deep.email') }}</p>
        <p>Please note: even after your account is terminated, some or all of your data may still be visible to others, including without limitation any data that has been (a) copied, stored, or disseminated by other users (including chat, doubts, leader-board ranking etc); (b) shared or disseminated by you or others (including chat, doubts, leader-board ranking etc); or (c) posted to a third-party platform. Even after your account is terminated, we retain your data for as long as we have a legitimate purpose to do so (and in accordance with applicable law), including to assist with legal obligations, resolve disputes, and enforce our agreements. We may retain and disclose such data pursuant to this Privacy Policy after your account has been terminated.</p>
        <p>If you wish to correct or delete your personal data, please email {{ config('deep.email') }}. or write to us at Attn: {{ config('deep.brand') }}, {{ config('deep.full_address') }}. Please allow up to 30 days for a response. For your protection, we may require that the request be sent through the email address associated with your account, and we may need to verify your identity before implementing your request. Please note that we retain certain data where we have a lawful basis to do so, including for mandatory record-keeping and to complete transactions.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">SECURITY</h2>
        <p>To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">COOKIES</h2>
        <p>We use cookies to maintain session of your user. It is not used to personally identify you on other websites.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">AGE OF CONSENT</h2>
        <p>By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">CHANGES TO THIS PRIVACY POLICY</h2>
        <p>We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website. If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.</p>
        <p>If our store is acquired or merged with another company, your information may be transferred to the new owners so that we may continue to sell products to you.</p>
        <h2 class="font-bold mt-3 mb-1 text-xl">QUESTIONS AND CONTACT INFORMATION</h2>
        <p>If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information, contact our Privacy Compliance Officer at {{ config('deep.email') }}.</p>
    </div>
</div>