<?php

namespace Deep\Pages\Http\Livewire\Pages;

use Livewire\Component;

use Deep\Pages\Models\Client;

class Clients extends Component
{
    // public $data=[
    //     [ "src" =>"sheraton.png", "name" => "Sheraton Hotel, Saket" ],
    //     [ "src" =>"bristol.jpg", "name" => "The Bristol hotel" ],
    //     [ "src" =>"carlson-wagonlit-travel.png", "name" => "Carlson Wagonlit Travel" ],
    //     [ "src" =>"ajit-bhawan.png", "name" => "Ajit Bhawan Jhodpur" ],
    //     [ "src" =>"welcomhotel-dwarka.jpg", "name" => "WelcomHotel, Dwarka" ],
    //     [ "src" =>"parkinn.png", "name" => "ParkInn" ],
    //     [ "src" =>"lemon-tree.jpg", "name" => "Lemon Tree" ],
    //     [ "src" =>"Jaisalkot.jpg", "name" => "Jaisalkot" ],
    //     [ "src" =>"PinkPark.jpg", "name" => "Pink Park" ],
    //     [ "src" =>"levante-logo.jpg", "name" => "Levante Hotel, Delhi" ],
    //     [ "src" =>"westface-logo.jpg", "name" => "Westtface Hotels" ],
    //     [ "src" =>"contitel-logo.jpg", "name" => "Haut Monde, Delhi" ],
    //     [ "src" =>"brys-logo.jpg", "name" => "Brys Caves, Almora" ],
    //     [ "src" =>"palmbliss-logo.jpg", "name" => "PalmBliss Resorts, Rishikesh" ],
    //     [ "src" =>"alpine-logo.jpg", "name" => "Alpine Chalet Resorts, Mukteshwar" ],
    //     [ "src" =>"jdc-logo.jpg", "name" => "Jaisalmer Desert Camp" ],
    //     [ "src" =>"revpro-logo.jpg", "name" => "Revpro Hotels" ],
    //     [ "src" =>"cng-logo.jpg", "name" => "Connect & Grow" ],
    //     [ "src" =>"trueloan.svg", "name" => "True Loans" ],
    //     [ "src" =>"cbr.jpg", "name" => "CBR Hospitals" ],
    //     [ "src" =>"eye-specialist.png", "name" => "Eye Specialist" ],
    //     [ "src" =>"shadanga.png", "name" => "Shadanga" ],
    //     [ "src" =>"whitesmile.png", "name" => "Whitesmile" ],
    //     [ "src" =>"miras-logo.png", "name" => "Miras Care" ],
    //     [ "src" =>"aaynabysimi.png", "name" => "Aayna by Simi" ],
    //     [ "src" =>"csel.png", "name" => "CSEL" ],
    //     [ "src" =>"delichic.png", "name" => "Deli Chic" ],
    //     [ "src" =>"petmetz.png", "name" => "Pet Metz" ],
    //     [ "src" =>"bblunt-logo.jpg", "name" => "BBlunt" ],
    //     [ "src" =>"stance-logo.jpg", "name" => "Stance, Canada" ],
    //     [ "src" =>"walnut-logo.jpg", "name" => "Walnut Grove, Canada" ],
    //     [ "src" =>"wisertech-logo.jpg", "name" => "WiserTech Solutions, Canada" ],
    //     [ "src" =>"temple.png", "name" => "Shree MahaLakshmi Temple" ],
    //     [ "src" =>"casley-logo.jpg", "name" => "Casley, India" ],
    //     [ "src" =>"milestone-logo.jpg", "name" => "Milestone, Dubai" ],
    //     [ "src" =>"mfilterit-logo.jpg", "name" => "mFilterit" ],
    //     [ "src" =>"edc-logo.jpg", "name" => "Ecole de Culinaire" ],
    //     [ "src" =>"shaebusters-logo.jpg", "name" => "Shake Busters" ],
    //     [ "src" =>"goolean-logo.jpg", "name" => "Brunhild Technology" ],
    //     [ "src" =>"ambiance-logo.jpg", "name" => "Ambiance Fly" ],
    //     [ "src" =>"radz-logo.jpg", "name" => "Radz Beauty" ],
    //     [ "src" =>"vibgyor.jpg", "name" => "Vibgyor" ],
    //     [ "src" =>"new.png", "name" => "Innovation Motive" ],
    //     [ "src" =>"zappfresh.jpg", "name" => "Zappfresh" ],
    //     [ "src" =>"Evergreen.jpg", "name" => "Evergreen" ],
    //     [ "src" =>"Daily-Delite.jpg", "name" => "Daily Delite" ],
    //     [ "src" =>"Fssai.jpg", "name" => "Fssai" ],
    //     [ "src" =>"Kanvic.jpg", "name" => "Kanvic" ],
    //     [ "src" =>"Globus.jpg", "name" => "Globus" ],
    //     [ "src" =>"Glamveda.jpg", "name" => "Glamveda" ],
    //     [ "src" =>"mibm-logo.jpg", "name" => "MIBM" ],
    //     [ "src" =>"startup-logo.jpg", "name" => "The Startup Lab" ],
    //     [ "src" =>"cxo-log.jpg", "name" => "CXO Forest" ],
    //     [ "src" =>"selfstorage-logo.jpg", "name" => "Self Storage" ],
    //     [ "src" =>"adecity-logo.jpg", "name" => "Adecity" ],
    //     [ "src" =>"alba-smart.jpg", "name" => "Alba Smart" ],
    //     [ "src" =>"intelly-jelly.jpg", "name" => "iNTELLYJELLY" ],
    //     [ "src" =>"eExpedise.jpg", "name" => "eExpedise" ],
    //     [ "src" =>"groovaroo-dance.jpg", "name" => "Groovaroo Dance" ],
    //     [ "src" =>"NRS.jpg", "name" => "NRS Kitchen" ],
    //     [ "src" =>"FGSI.jpg", "name" => "FGSI" ],
    //     [ "src" =>"jump.jpg", "name" => "Jumpsum" ],
    //     [ "src" =>"Karpets.jpg", "name" => "Karpets by RKS" ],
    //     [ "src" =>"Metier.jpg", "name" => "Metier Store" ],
    //     [ "src" =>"Myedubag.jpg", "name" => "Myedubag" ],
    //     [ "src" =>"profiling-logo.png", "name" => "Profiling" ],
    //     [ "src" =>"trademark-dukan.jpg", "name" => "Trademark Dukan" ],
    //     [ "src" =>"Satranga.jpg", "name" => "Satranga" ],
    //     [ "src" =>"TBS.jpg", "name" => "Total Bid Solutions" ],
    //     [ "src" =>"techbridge.jpg", "name" => "Techbridge Labs" ],
    //     [ "src" =>"we-chaffer.jpg", "name" => "We Chaffer" ],
    //     [ "src" =>"Squizzl.jpg", "name" => "Squizzl" ],
    //     [ "src" =>"aoc.png", "name" => "AOC Gurgaon" ],
    //     [ "src" =>"hac-logo.jpg", "name" => "Hac Way" ],
    //     [ "src" =>"sanidhaya.png", "name" => "Sanidhaya" ],
    //     [ "src" =>"bizsutra.svg", "name" => "Biz Sutra" ],
    //     [ "src" =>"tbh-logo.jpg", "name" => "TBH Circle" ],
    //     [ "src" =>"saukhyam-logo.jpg", "name" => "Saukhyam" ],
    //     [ "src" =>"pynet-logo.jpg", "name" => "Pynet" ],
    //     [ "src" =>"sbs-logo.jpg", "name" => "SBS Legal Solutions" ],
    //     [ "src" =>"kion-logo.jpg", "name" => "Kion Overseas" ],
    //     [ "src" =>"jsconsulting-logo.jpg", "name" => "JS Consulting" ],
    //     [ "src" =>"amina-logo.jpg", "name" => "Amina Boutique" ],
    //     [ "src" =>"exmyb-logo.jpg", "name" => "Exmyb" ],
    //     [ "src" =>"cbc-logo.jpg", "name" => "Chinese Bowl Company" ],
    //     [ "src" =>"ich-logo.jpg", "name" => "Indian Curry House" ],
    //     [ "src" =>"maghol-logo.jpg", "name" => "Magical Holidays" ],
    //     [ "src" =>"mose-logo.jpg", "name" => "Magical Overseas Education" ],
    //     [ "src" =>"fintree.png", "name" => "Fintree Money" ],
    //     [ "src" =>"vaibhavlaxmi.png", "name" => "Vaibhav Laxmi" ],
    //     [ "src" =>"sapna-khemani.png", "name" => "Sapna Khemani" ],
    //     [ "src" =>"infoclab.png", "name" => "Info Clab" ],
    //     [ "src" =>"aayushi.png", "name" => "Aayushi" ],
    //     [ "src" =>"anckona.png", "name" => "Anckona" ],
    //     [ "src" =>"erinadus.png", "name" => "Erinadus" ],
    //     [ "src" =>"hindraj.png", "name" => "Hindraj Tea" ],
    //     [ "src" =>"ocs.png", "name" => "OCS" ],
    //     [ "src" =>"pujarambh.jpg", "name" => "Pujarambh" ],
    //     [ "src" =>"gkb.png", "name" => "House of GKB" ],
    //     [ "src" =>"mnlgluck.png", "name" => "MNL Gluck" ],
    //     [ "src" =>"pnaorigine-logo.jpg", "name" => "PNA Origine" ],
    //     [ "src" =>"revxads-logo.png", "name" => "Revxads" ],
    //     [ "src" =>"tgop.jpg", "name" => "TGOP" ],
    //     [ "src" =>"tedco-education.jpg", "name" => "Tedco Education" ],
    //     [ "src" =>"mindtribe.jpg", "name" => "Mindtribe" ],
    //     [ "src" =>"mugigs.jpg", "name" => "Mugigs" ],
    //     [ "src" =>"house-of-urjaa.jpg", "name" => "House of Urjaa" ],
    //     [ "src" =>"lohewala.jpg", "name" => "Lohewala" ],
    //     [ "src" =>"global-diction-studio.jpg", "name" => "Global Diction Studio" ],
    //     [ "src" =>"horenso.jpg", "name" => "HORENSO" ],
    //     [ "src" =>"trident-energy-india.jpg", "name" => "Trident Energy" ],
    //     [ "src" =>"the-pakwan-factory.jpg", "name" => "Pakwan Factory" ],
    //     [ "src" =>"propelld.jpg", "name" => "Propelld" ],
    // ];

    public $data;
    
    public function mount(){
        $this->data = Client::with('media:id,alt,path')
                        ->active()->orderBy('display_order', 'ASC')->get();
    }

    public function render(){ return view('deep::livewire.pages.clients')->layout('layouts.admin'); }
}